version: '3.0'
services:
  rasa_core:
    image: rasa/rasa_core:latest
    ports:
      - 4112:5005
    volumes:
      - ./models/rasa_core:/app/models
      - ./config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
  rasa_nlu:
    image: rasa/rasa_nlu:latest-tensorflow
    volumes:
      - ./models/rasa_nlu:/app/models
      - ./config:/app/config
    command:
      - start
      - --path
      - models
      - -c
      - config/nlu_config.yml
  action_server:
    image: rasa/rasa_core_sdk:latest
    volumes:
      - ./actions:/app/actions