language: zh
pipeline:
- name: "tokenizer_jieba"
- name: "tensorflow_embedding"

policies:
  - name: KerasPolicy
    epochs: 200
    batch_size: 50
    max_training_samples: 300
  - name: FallbackPolicy
  - name: MemoizationPolicy
