language: "zh"

pipeline:
- name: "tokenizer_jieba"
- name: "ner_crf"
- name: "ner_duckling"
  language: "zh$core"
  dimensions: [ "city", "date"]
- name: "jieba_pseg_extractor"
  part_of_speech: ["nr"]
- name: "intent_featurizer_count_vectors"
  OOV_token: oov
  token_pattern: '(?u)\b\w+\b'
- name: "intent_classifier_tensorflow_embedding"

policies:
  - name: KerasPolicy
    epochs: 200
    batch_size: 50
    max_training_samples: 300
  - name: FallbackPolicy
  - name: MemoizationPolicy
